### ISSUE TITLE
Wrong api url if neos is operating on a relative path

### ISSUE THREAD

**Issue by johannessteu** [breadlesscode/neos-simple-editor-extend#1]
This line https://github.com/breadlesscode/neos-simple-editor-extend/blob/master/Resources/Private/UiPlugin/src/manifest.js#L9

might be an issue if your neos is operating on a relative path like `https://site.com/somePath`.
The api url will result in `https://site.com/breadlesscode/editor-config` instead of `https://site.com/somePath/breadlesscode/editor-config`

**Comment by skurfuerst** [comment]
Hey,

actually you might want to get rid of that behavior, and use "frontendConfiguration" to pass the config to the Editor. The problem of having this via API is that it might load too late -- the manifests are expected to be called synchronously; so they should not call out via AJAX.

All the best :) 
Sebastian

**Comment by breadlesscode** [comment]
@skurfuerst Thanks for the nice hint. :) But I did not succeed with `globalRegistry.get('frontendConfiguration').get('Your.Own:Package').someKey`. 

Do you know what I'm doing wrong?
This is what I tried: https://github.com/breadlesscode/neos-simple-editor-extend/blob/frontend-configuration-demo/Resources/Private/UiPlugin/src/manifest.js#L10-L18

Output:
```
Has: false
Get: null
Registry: 
0: {key: "legacy", value: {…}}
1: {key: "editPreviewModes", value: {…}}
2: {key: "hotkeys", value: {…}}
3: {key: "defaultInlineEditor", value: {…}}
4: {key: "Breadlesscode.SimpleEditorExtend", value: {…}}
length: 5
__proto__: Array(0)
```

Thanks again for your feedback :heart:

**Comment by skurfuerst** [comment]
@breadlesscode Hey :)

unfortunately in the manifest, the frontendConfiguration registry is not yet filled. However, you get a 2nd parameter passed in which is an object containing a "frontendConfiguration"  key.

So, you are able to do the following:

```
manifest('...', {}, (globalRegistry, {frontendConfiguration}) => {
   console.log(frontendConfiguration['Your.Package:Key']);
});
```

We definitely lack documentation there.... If you like, I would be glad to give you access to docs.neos.io backend - and then you could help us adding this to the docs :-) (only if you have time).

All the best <3 Sebastian
